import {
  STAGING_PREFIX,
  STAGING_VENDOR_A_UID,
  STAGING_VENDOR_B_UID,
  STAGING_VENDOR_C_UID,
  VENDOR_BRANDS,
  stagingProductImages,
} from './seed-constants';

export interface SeedProduct {
  id: string;
  tailor_id: string;
  tailor: string;
  title: string;
  description: string;
  wear_category: string;
  type: 'ready_to_wear' | 'bespoke' | 'ready-to-wear';
  priceNgn: number;
  images: string[];
  tags: string[];
  wear_quantity?: number;
  sizes?: string[];
}

/** 18 products across 3 vendors — realistic African fashion names. */
export const SEED_PRODUCT_CATALOG: SeedProduct[] = [
  {
    id: `${STAGING_PREFIX}-prod-001`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Oshodi Sunrise Ankara Maxi',
    description: 'Floor-length ankara maxi with hand-finished hem. Ready to ship in 3–5 days.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 48500,
    images: stagingProductImages(0),
    tags: ['ankara', 'maxi', 'ready-to-wear'],
    wear_quantity: 12,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-002`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Lagos Nights Silk Kaftan',
    description: 'Relaxed silk-blend kaftan for evening wear. Lightweight and breathable.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 62000,
    images: stagingProductImages(1),
    tags: ['kaftan', 'silk', 'evening'],
    wear_quantity: 8,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-003`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Adire Indigo Wrap Dress',
    description: 'Traditional adire-inspired wrap dress with modern silhouette.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 39500,
    images: stagingProductImages(2),
    tags: ['adire', 'wrap', 'indigo'],
    wear_quantity: 15,
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: `${STAGING_PREFIX}-prod-004`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Accra Breeze Linen Co-ord',
    description: 'Two-piece linen set — crop top and wide-leg trouser for warm climates.',
    wear_category: 'suit',
    type: 'ready_to_wear',
    priceNgn: 55000,
    images: stagingProductImages(3),
    tags: ['linen', 'co-ord', 'resort'],
    wear_quantity: 10,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: `${STAGING_PREFIX}-prod-005`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Nubian Gold Print Blazer',
    description: 'Structured blazer in gold-accent African wax print.',
    wear_category: 'blazer',
    type: 'ready_to_wear',
    priceNgn: 72000,
    images: stagingProductImages(4),
    tags: ['blazer', 'wax-print', 'office'],
    wear_quantity: 6,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-006`,
    tailor_id: STAGING_VENDOR_A_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_A_UID],
    title: 'Aso Ebi Celebration Dress',
    description: 'Vibrant party dress designed for weddings and owambe celebrations.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 89000,
    images: stagingProductImages(5),
    tags: ['aso-ebi', 'party', 'wedding-guest'],
    wear_quantity: 5,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-007`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Savanna Bespoke Two-Piece Suit',
    description: 'Custom-tailored suit with bespoke fitting session included.',
    wear_category: 'suit',
    type: 'bespoke',
    priceNgn: 185000,
    images: stagingProductImages(6),
    tags: ['bespoke', 'suit', 'formal'],
  },
  {
    id: `${STAGING_PREFIX}-prod-008`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Nile Crescent Agbada Set',
    description: 'Hand-embroidered agbada with matching cap. Made to measure.',
    wear_category: 'agbada',
    type: 'bespoke',
    priceNgn: 220000,
    images: stagingProductImages(7),
    tags: ['agbada', 'traditional', 'ceremony'],
  },
  {
    id: `${STAGING_PREFIX}-prod-009`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Dakar Ember Wedding Gown',
    description: 'Custom bridal gown with optional train and beadwork.',
    wear_category: 'gown',
    type: 'bespoke',
    priceNgn: 350000,
    images: stagingProductImages(8),
    tags: ['bridal', 'gown', 'custom'],
  },
  {
    id: `${STAGING_PREFIX}-prod-010`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Kente Horizon Dashiki Shirt',
    description: 'Bespoke dashiki shirt with kente panel detailing.',
    wear_category: 'shirt',
    type: 'bespoke',
    priceNgn: 45000,
    images: stagingProductImages(9),
    tags: ['dashiki', 'kente', 'menswear'],
  },
  {
    id: `${STAGING_PREFIX}-prod-011`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Sahara Nomad Linen Trousers',
    description: 'Relaxed bespoke trousers with side adjusters.',
    wear_category: 'trouser',
    type: 'bespoke',
    priceNgn: 38000,
    images: stagingProductImages(10),
    tags: ['trousers', 'linen', 'menswear'],
  },
  {
    id: `${STAGING_PREFIX}-prod-012`,
    tailor_id: STAGING_VENDOR_B_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_B_UID],
    title: 'Calabar Pearl Beaded Gown',
    description: 'Evening gown with hand-sewn pearl embellishment.',
    wear_category: 'gown',
    type: 'bespoke',
    priceNgn: 275000,
    images: stagingProductImages(11),
    tags: ['gown', 'beaded', 'galas'],
  },
  {
    id: `${STAGING_PREFIX}-prod-013`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Zulu Horizon Midi Skirt',
    description: 'High-waist midi skirt in bold geometric print.',
    wear_category: 'skirt',
    type: 'ready_to_wear',
    priceNgn: 28000,
    images: stagingProductImages(12),
    tags: ['skirt', 'midi', 'print'],
    wear_quantity: 20,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-014`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Kumasi Kente Blazer',
    description: 'Unisex kente blazer — limited ready-to-wear run.',
    wear_category: 'blazer',
    type: 'ready_to_wear',
    priceNgn: 95000,
    images: stagingProductImages(13),
    tags: ['kente', 'blazer', 'unisex'],
    wear_quantity: 7,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-015`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Ibile Heritage Aso-Oke Top',
    description: 'Structured top woven from authentic aso-oke strips.',
    wear_category: 'shirt',
    type: 'ready_to_wear',
    priceNgn: 42000,
    images: stagingProductImages(14),
    tags: ['aso-oke', 'heritage', 'top'],
    wear_quantity: 9,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: `${STAGING_PREFIX}-prod-016`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Cape Town Coral Maxi',
    description: 'Flowing coral-toned maxi for beach and resort events.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 51000,
    images: stagingProductImages(15),
    tags: ['maxi', 'resort', 'coral'],
    wear_quantity: 11,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: `${STAGING_PREFIX}-prod-017`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Maasai Coral Evening Dress',
    description: 'Statement evening dress with coral bead-inspired neckline.',
    wear_category: 'dress',
    type: 'ready_to_wear',
    priceNgn: 78000,
    images: stagingProductImages(16),
    tags: ['evening', 'statement', 'beaded'],
    wear_quantity: 4,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: `${STAGING_PREFIX}-prod-018`,
    tailor_id: STAGING_VENDOR_C_UID,
    tailor: VENDOR_BRANDS[STAGING_VENDOR_C_UID],
    title: 'Timbuktu Nomad Tunic',
    description: 'Loose tunic in earth tones — pairs with jeans or tailored trousers.',
    wear_category: 'shirt',
    type: 'ready_to_wear',
    priceNgn: 33500,
    images: stagingProductImages(17),
    tags: ['tunic', 'casual', 'unisex'],
    wear_quantity: 14,
    sizes: ['S', 'M', 'L', 'XL'],
  },
];
