/**
 * Location data service for country, state, and city selection
 */

export interface Country {
	name: string;
	code: string;
	dialCode: string;
}

export interface State {
	name: string;
	code: string;
}

export interface City {
	name: string;
}

// Comprehensive country list with dial codes
export const COUNTRIES: Country[] = [
	{ name: "United States", code: "US", dialCode: "+1" },
	{ name: "United Kingdom", code: "GB", dialCode: "+44" },
	{ name: "Canada", code: "CA", dialCode: "+1" },
	{ name: "Nigeria", code: "NG", dialCode: "+234" },
	{ name: "Ghana", code: "GH", dialCode: "+233" },
	{ name: "Kenya", code: "KE", dialCode: "+254" },
	{ name: "South Africa", code: "ZA", dialCode: "+27" },
	{ name: "Egypt", code: "EG", dialCode: "+20" },
	{ name: "Morocco", code: "MA", dialCode: "+212" },
	{ name: "Ethiopia", code: "ET", dialCode: "+251" },
	{ name: "Tanzania", code: "TZ", dialCode: "+255" },
	{ name: "Uganda", code: "UG", dialCode: "+256" },
	{ name: "Rwanda", code: "RW", dialCode: "+250" },
	{ name: "Senegal", code: "SN", dialCode: "+221" },
	{ name: "Ivory Coast", code: "CI", dialCode: "+225" },
	{ name: "Cameroon", code: "CM", dialCode: "+237" },
	{ name: "Algeria", code: "DZ", dialCode: "+213" },
	{ name: "Angola", code: "AO", dialCode: "+244" },
	{ name: "Botswana", code: "BW", dialCode: "+267" },
	{ name: "Burkina Faso", code: "BF", dialCode: "+226" },
	{ name: "Burundi", code: "BI", dialCode: "+257" },
	{ name: "Cabo Verde", code: "CV", dialCode: "+238" },
	{ name: "Central African Republic", code: "CF", dialCode: "+236" },
	{ name: "Chad", code: "TD", dialCode: "+235" },
	{ name: "Comoros", code: "KM", dialCode: "+269" },
	{ name: "Democratic Republic of the Congo", code: "CD", dialCode: "+243" },
	{ name: "Djibouti", code: "DJ", dialCode: "+253" },
	{ name: "Equatorial Guinea", code: "GQ", dialCode: "+240" },
	{ name: "Eritrea", code: "ER", dialCode: "+291" },
	{ name: "Eswatini", code: "SZ", dialCode: "+268" },
	{ name: "Gabon", code: "GA", dialCode: "+241" },
	{ name: "Gambia", code: "GM", dialCode: "+220" },
	{ name: "Guinea", code: "GN", dialCode: "+224" },
	{ name: "Guinea-Bissau", code: "GW", dialCode: "+245" },
	{ name: "Lesotho", code: "LS", dialCode: "+266" },
	{ name: "Liberia", code: "LR", dialCode: "+231" },
	{ name: "Libya", code: "LY", dialCode: "+218" },
	{ name: "Madagascar", code: "MG", dialCode: "+261" },
	{ name: "Malawi", code: "MW", dialCode: "+265" },
	{ name: "Mali", code: "ML", dialCode: "+223" },
	{ name: "Mauritania", code: "MR", dialCode: "+222" },
	{ name: "Mauritius", code: "MU", dialCode: "+230" },
	{ name: "Mozambique", code: "MZ", dialCode: "+258" },
	{ name: "Namibia", code: "NA", dialCode: "+264" },
	{ name: "Niger", code: "NE", dialCode: "+227" },
	{ name: "São Tomé and Príncipe", code: "ST", dialCode: "+239" },
	{ name: "Seychelles", code: "SC", dialCode: "+248" },
	{ name: "Sierra Leone", code: "SL", dialCode: "+232" },
	{ name: "Somalia", code: "SO", dialCode: "+252" },
	{ name: "South Sudan", code: "SS", dialCode: "+211" },
	{ name: "Togo", code: "TG", dialCode: "+228" },
	{ name: "Tunisia", code: "TN", dialCode: "+216" },
	{ name: "Zambia", code: "ZM", dialCode: "+260" },
	{ name: "Zimbabwe", code: "ZW", dialCode: "+263" },
	{ name: "Australia", code: "AU", dialCode: "+61" },
	{ name: "Brazil", code: "BR", dialCode: "+55" },
	{ name: "Argentina", code: "AR", dialCode: "+54" },
	{ name: "Chile", code: "CL", dialCode: "+56" },
	{ name: "Colombia", code: "CO", dialCode: "+57" },
	{ name: "Peru", code: "PE", dialCode: "+51" },
	{ name: "Venezuela", code: "VE", dialCode: "+58" },
	{ name: "Mexico", code: "MX", dialCode: "+52" },
	{ name: "France", code: "FR", dialCode: "+33" },
	{ name: "Germany", code: "DE", dialCode: "+49" },
	{ name: "Italy", code: "IT", dialCode: "+39" },
	{ name: "Spain", code: "ES", dialCode: "+34" },
	{ name: "Portugal", code: "PT", dialCode: "+351" },
	{ name: "Belgium", code: "BE", dialCode: "+32" },
	{ name: "Netherlands", code: "NL", dialCode: "+31" },
	{ name: "Switzerland", code: "CH", dialCode: "+41" },
	{ name: "Austria", code: "AT", dialCode: "+43" },
	{ name: "Sweden", code: "SE", dialCode: "+46" },
	{ name: "Norway", code: "NO", dialCode: "+47" },
	{ name: "Denmark", code: "DK", dialCode: "+45" },
	{ name: "Finland", code: "FI", dialCode: "+358" },
	{ name: "Poland", code: "PL", dialCode: "+48" },
	{ name: "Czech Republic", code: "CZ", dialCode: "+420" },
	{ name: "Hungary", code: "HU", dialCode: "+36" },
	{ name: "Romania", code: "RO", dialCode: "+40" },
	{ name: "Greece", code: "GR", dialCode: "+30" },
	{ name: "Turkey", code: "TR", dialCode: "+90" },
];

// States/Provinces by country
export const STATES_BY_COUNTRY: Record<string, State[]> = {
	US: [
		{ name: "Alabama", code: "AL" },
		{ name: "Alaska", code: "AK" },
		{ name: "Arizona", code: "AZ" },
		{ name: "Arkansas", code: "AR" },
		{ name: "California", code: "CA" },
		{ name: "Colorado", code: "CO" },
		{ name: "Connecticut", code: "CT" },
		{ name: "Delaware", code: "DE" },
		{ name: "Florida", code: "FL" },
		{ name: "Georgia", code: "GA" },
		{ name: "Hawaii", code: "HI" },
		{ name: "Idaho", code: "ID" },
		{ name: "Illinois", code: "IL" },
		{ name: "Indiana", code: "IN" },
		{ name: "Iowa", code: "IA" },
		{ name: "Kansas", code: "KS" },
		{ name: "Kentucky", code: "KY" },
		{ name: "Louisiana", code: "LA" },
		{ name: "Maine", code: "ME" },
		{ name: "Maryland", code: "MD" },
		{ name: "Massachusetts", code: "MA" },
		{ name: "Michigan", code: "MI" },
		{ name: "Minnesota", code: "MN" },
		{ name: "Mississippi", code: "MS" },
		{ name: "Missouri", code: "MO" },
		{ name: "Montana", code: "MT" },
		{ name: "Nebraska", code: "NE" },
		{ name: "Nevada", code: "NV" },
		{ name: "New Hampshire", code: "NH" },
		{ name: "New Jersey", code: "NJ" },
		{ name: "New Mexico", code: "NM" },
		{ name: "New York", code: "NY" },
		{ name: "North Carolina", code: "NC" },
		{ name: "North Dakota", code: "ND" },
		{ name: "Ohio", code: "OH" },
		{ name: "Oklahoma", code: "OK" },
		{ name: "Oregon", code: "OR" },
		{ name: "Pennsylvania", code: "PA" },
		{ name: "Rhode Island", code: "RI" },
		{ name: "South Carolina", code: "SC" },
		{ name: "South Dakota", code: "SD" },
		{ name: "Tennessee", code: "TN" },
		{ name: "Texas", code: "TX" },
		{ name: "Utah", code: "UT" },
		{ name: "Vermont", code: "VT" },
		{ name: "Virginia", code: "VA" },
		{ name: "Washington", code: "WA" },
		{ name: "West Virginia", code: "WV" },
		{ name: "Wisconsin", code: "WI" },
		{ name: "Wyoming", code: "WY" },
	],
	GB: [
		{ name: "England", code: "ENG" },
		{ name: "Scotland", code: "SCT" },
		{ name: "Wales", code: "WLS" },
		{ name: "Northern Ireland", code: "NIR" },
	],
	CA: [
		{ name: "Alberta", code: "AB" },
		{ name: "British Columbia", code: "BC" },
		{ name: "Manitoba", code: "MB" },
		{ name: "New Brunswick", code: "NB" },
		{ name: "Newfoundland and Labrador", code: "NL" },
		{ name: "Nova Scotia", code: "NS" },
		{ name: "Ontario", code: "ON" },
		{ name: "Prince Edward Island", code: "PE" },
		{ name: "Quebec", code: "QC" },
		{ name: "Saskatchewan", code: "SK" },
	],
	NG: [
		{ name: "Abia", code: "AB" },
		{ name: "Adamawa", code: "AD" },
		{ name: "Akwa Ibom", code: "AK" },
		{ name: "Anambra", code: "AN" },
		{ name: "Bauchi", code: "BA" },
		{ name: "Bayelsa", code: "BY" },
		{ name: "Benue", code: "BE" },
		{ name: "Borno", code: "BO" },
		{ name: "Cross River", code: "CR" },
		{ name: "Delta", code: "DE" },
		{ name: "Ebonyi", code: "EB" },
		{ name: "Edo", code: "ED" },
		{ name: "Ekiti", code: "EK" },
		{ name: "Enugu", code: "EN" },
		{ name: "FCT", code: "FC" },
		{ name: "Gombe", code: "GO" },
		{ name: "Imo", code: "IM" },
		{ name: "Jigawa", code: "JI" },
		{ name: "Kaduna", code: "KD" },
		{ name: "Kano", code: "KN" },
		{ name: "Katsina", code: "KT" },
		{ name: "Kebbi", code: "KE" },
		{ name: "Kogi", code: "KO" },
		{ name: "Kwara", code: "KW" },
		{ name: "Lagos", code: "LA" },
		{ name: "Nasarawa", code: "NA" },
		{ name: "Niger", code: "NI" },
		{ name: "Ogun", code: "OG" },
		{ name: "Ondo", code: "ON" },
		{ name: "Osun", code: "OS" },
		{ name: "Oyo", code: "OY" },
		{ name: "Plateau", code: "PL" },
		{ name: "Rivers", code: "RI" },
		{ name: "Sokoto", code: "SO" },
		{ name: "Taraba", code: "TA" },
		{ name: "Yobe", code: "YO" },
		{ name: "Zamfara", code: "ZA" },
	],
	GH: [
		{ name: "Greater Accra", code: "AA" },
		{ name: "Ashanti", code: "AH" },
		{ name: "Brong-Ahafo", code: "BA" },
		{ name: "Central", code: "CP" },
		{ name: "Eastern", code: "EP" },
		{ name: "Northern", code: "NP" },
		{ name: "Upper East", code: "UE" },
		{ name: "Upper West", code: "UW" },
		{ name: "Volta", code: "TV" },
		{ name: "Western", code: "WP" },
	],
	KE: [
		{ name: "Nairobi", code: "NBO" },
		{ name: "Mombasa", code: "MBA" },
		{ name: "Kisumu", code: "KSM" },
		{ name: "Nakuru", code: "NKR" },
		{ name: "Eldoret", code: "ELD" },
		{ name: "Kiambu", code: "KIA" },
		{ name: "Machakos", code: "MCH" },
		{ name: "Kakamega", code: "KKG" },
	],
	ZA: [
		{ name: "Eastern Cape", code: "EC" },
		{ name: "Free State", code: "FS" },
		{ name: "Gauteng", code: "GT" },
		{ name: "KwaZulu-Natal", code: "NL" },
		{ name: "Limpopo", code: "LP" },
		{ name: "Mpumalanga", code: "MP" },
		{ name: "Northern Cape", code: "NC" },
		{ name: "North West", code: "NW" },
		{ name: "Western Cape", code: "WC" },
	],
	DZ: [
		{ name: "Algiers", code: "AL" },
		{ name: "Oran", code: "OR" },
		{ name: "Constantine", code: "CN" },
		{ name: "Blida", code: "BL" },
		{ name: "Batna", code: "BT" },
		{ name: "Annaba", code: "AN" },
		{ name: "Sétif", code: "SE" },
		{ name: "Sidi Bel Abbès", code: "SB" },
		{ name: "Biskra", code: "BS" },
		{ name: "Tébessa", code: "TE" },
	],
	AO: [
		{ name: "Luanda", code: "LU" },
		{ name: "Huambo", code: "HU" },
		{ name: "Benguela", code: "BG" },
		{ name: "Cabinda", code: "CA" },
		{ name: "Kwanza Norte", code: "KN" },
		{ name: "Kwanza Sul", code: "KS" },
		{ name: "Huila", code: "HL" },
		{ name: "Bie", code: "BI" },
		{ name: "Cuando Cubango", code: "CC" },
		{ name: "Moxico", code: "MO" },
	],
	BW: [
		{ name: "Gaborone", code: "GB" },
		{ name: "Francistown", code: "FB" },
		{ name: "Central District", code: "CE" },
		{ name: "Chobe District", code: "CH" },
		{ name: "Kgalagadi District", code: "KG" },
		{ name: "Kgatleng District", code: "KL" },
		{ name: "Kweneng District", code: "KW" },
		{ name: "North East District", code: "NE" },
		{ name: "North West District", code: "NW" },
		{ name: "South East District", code: "SE" },
	],
	CM: [
		{ name: "Littoral", code: "LT" },
		{ name: "Southwest", code: "SW" },
		{ name: "Northwest", code: "NW" },
		{ name: "West", code: "WE" },
		{ name: "South", code: "SU" },
		{ name: "Centre", code: "CE" },
		{ name: "East", code: "ES" },
		{ name: "Far North", code: "FN" },
		{ name: "North", code: "NO" },
		{ name: "Adamaoua", code: "AD" },
	],
	AU: [
		{ name: "New South Wales", code: "NSW" },
		{ name: "Queensland", code: "QLD" },
		{ name: "South Australia", code: "SA" },
		{ name: "Tasmania", code: "TAS" },
		{ name: "Victoria", code: "VIC" },
		{ name: "Western Australia", code: "WA" },
		{ name: "Australian Capital Territory", code: "ACT" },
		{ name: "Northern Territory", code: "NT" },
	],
	BR: [
		{ name: "São Paulo", code: "SP" },
		{ name: "Rio de Janeiro", code: "RJ" },
		{ name: "Minas Gerais", code: "MG" },
		{ name: "Bahia", code: "BA" },
		{ name: "Rio Grande do Sul", code: "RS" },
		{ name: "Paraná", code: "PR" },
		{ name: "Pernambuco", code: "PE" },
		{ name: "Ceará", code: "CE" },
		{ name: "Maranhão", code: "MA" },
		{ name: "Santa Catarina", code: "SC" },
	],
	FR: [
		{ name: "Île-de-France", code: "IDF" },
		{ name: "Provence-Alpes-Côte d'Azur", code: "PAC" },
		{ name: "Auvergne-Rhône-Alpes", code: "ARA" },
		{ name: "Normandy", code: "NOR" },
		{ name: "Hauts-de-France", code: "HDF" },
		{ name: "Grand Est", code: "GES" },
		{ name: "Brittany", code: "BRE" },
		{ name: "Occitanie", code: "OCC" },
		{ name: "Centre-Val de Loire", code: "CVL" },
		{ name: "Bourgogne-Franche-Comté", code: "BFC" },
	],
	DE: [
		{ name: "Baden-Württemberg", code: "BW" },
		{ name: "Bavaria", code: "BY" },
		{ name: "Berlin", code: "BE" },
		{ name: "Brandenburg", code: "BB" },
		{ name: "Bremen", code: "HB" },
		{ name: "Hamburg", code: "HH" },
		{ name: "Hesse", code: "HE" },
		{ name: "Lower Saxony", code: "NI" },
		{ name: "Mecklenburg-Vorpommern", code: "MV" },
		{ name: "North Rhine-Westphalia", code: "NW" },
	],
	IT: [
		{ name: "Lombardy", code: "LOM" },
		{ name: "Lazio", code: "LAZ" },
		{ name: "Campania", code: "CAM" },
		{ name: "Veneto", code: "VEN" },
		{ name: "Emilia-Romagna", code: "EMR" },
		{ name: "Tuscany", code: "TUS" },
		{ name: "Piedmont", code: "PIE" },
		{ name: "Apulia", code: "PUG" },
		{ name: "Calabria", code: "CAL" },
		{ name: "Sicily", code: "SIC" },
	],
	ES: [
		{ name: "Andalusia", code: "AND" },
		{ name: "Catalonia", code: "CAT" },
		{ name: "Madrid", code: "MAD" },
		{ name: "Valencia", code: "VAL" },
		{ name: "Galicia", code: "GAL" },
		{ name: "Castile and León", code: "CL" },
		{ name: "Basque Country", code: "PV" },
		{ name: "Canary Islands", code: "CAN" },
		{ name: "Castilla-La Mancha", code: "CM" },
		{ name: "Aragon", code: "ARA" },
	],
	JP: [
		{ name: "Tokyo", code: "13" },
		{ name: "Osaka", code: "27" },
		{ name: "Kanagawa", code: "14" },
		{ name: "Aichi", code: "23" },
		{ name: "Saitama", code: "11" },
		{ name: "Chiba", code: "12" },
		{ name: "Hyogo", code: "28" },
		{ name: "Fukuoka", code: "40" },
		{ name: "Shizuoka", code: "22" },
		{ name: "Hokkaido", code: "01" },
	],
	IN: [
		{ name: "Maharashtra", code: "MH" },
		{ name: "Uttar Pradesh", code: "UP" },
		{ name: "Tamil Nadu", code: "TN" },
		{ name: "Karnataka", code: "KA" },
		{ name: "Gujarat", code: "GJ" },
		{ name: "Rajasthan", code: "RJ" },
		{ name: "Haryana", code: "HR" },
		{ name: "Kerala", code: "KL" },
		{ name: "Punjab", code: "PB" },
		{ name: "West Bengal", code: "WB" },
	],
};

// Major cities by state/country
export const CITIES_BY_STATE: Record<string, Record<string, City[]>> = {
	US: {
		CA: [
			{ name: "Los Angeles" },
			{ name: "San Francisco" },
			{ name: "San Diego" },
			{ name: "San Jose" },
			{ name: "Sacramento" },
			{ name: "Oakland" },
			{ name: "Fresno" },
			{ name: "Long Beach" },
			{ name: "Anaheim" },
			{ name: "Santa Ana" },
			{ name: "Riverside" },
			{ name: "Stockton" },
			{ name: "Irvine" },
			{ name: "Bakersfield" },
		],
		NY: [
			{ name: "New York City" },
			{ name: "Buffalo" },
			{ name: "Rochester" },
			{ name: "Albany" },
			{ name: "Syracuse" },
			{ name: "Yonkers" },
			{ name: "New Rochelle" },
			{ name: "Mount Vernon" },
		],
		TX: [
			{ name: "Houston" },
			{ name: "Dallas" },
			{ name: "Austin" },
			{ name: "San Antonio" },
			{ name: "Fort Worth" },
			{ name: "El Paso" },
			{ name: "Arlington" },
			{ name: "Corpus Christi" },
			{ name: "Plano" },
		],
		FL: [
			{ name: "Miami" },
			{ name: "Orlando" },
			{ name: "Tampa" },
			{ name: "Jacksonville" },
			{ name: "Fort Lauderdale" },
			{ name: "St. Petersburg" },
			{ name: "Tallahassee" },
			{ name: "Hialeah" },
			{ name: "Port St. Lucie" },
		],
		IL: [
			{ name: "Chicago" },
			{ name: "Aurora" },
			{ name: "Naperville" },
			{ name: "Joliet" },
			{ name: "Rockford" },
		],
		GA: [
			{ name: "Atlanta" },
			{ name: "Augusta" },
			{ name: "Columbus" },
			{ name: "Savannah" },
			{ name: "Athens" },
		],
	},
	NG: {
		LA: [
			{ name: "Ikeja" },
			{ name: "Victoria Island" },
			{ name: "Lekki" },
			{ name: "Surulere" },
			{ name: "Yaba" },
			{ name: "Ikoyi" },
			{ name: "Ajah" },
			{ name: "Maryland" },
			{ name: "Apapa" },
			{ name: "Oshodi" },
			{ name: "Mushin" },
			{ name: "Agege" },
			{ name: "Alimosho" },
			{ name: "Badagry" },
			{ name: "Epe" },
			{ name: "Ikorodu" },
			{ name: "Kosofe" },
			{ name: "Lagos Island" },
			{ name: "Ojo" },
			{ name: "Somolu" },
		],
		FC: [
			{ name: "Abuja" },
			{ name: "Gwagwalada" },
			{ name: "Kuje" },
			{ name: "Bwari" },
			{ name: "Abaji" },
			{ name: "Kwali" },
			{ name: "Garki" },
			{ name: "Wuse" },
			{ name: "Maitama" },
			{ name: "Asokoro" },
			{ name: "Gwarinpa" },
			{ name: "Kubwa" },
			{ name: "Lugbe" },
			{ name: "Nyanya" },
			{ name: "Karu" },
		],
		KN: [
			{ name: "Kano" },
			{ name: "Fagge" },
			{ name: "Gwale" },
			{ name: "Dala" },
			{ name: "Kumbotso" },
			{ name: "Nassarawa" },
			{ name: "Tarauni" },
			{ name: "Ungogo" },
		],
		RI: [
			{ name: "Port Harcourt" },
			{ name: "Obio-Akpor" },
			{ name: "Eleme" },
			{ name: "Okrika" },
			{ name: "Bonny" },
			{ name: "Degema" },
		],
		OG: [
			{ name: "Abeokuta" },
			{ name: "Ijebu Ode" },
			{ name: "Sagamu" },
			{ name: "Ota" },
			{ name: "Ilaro" },
		],
		OY: [
			{ name: "Ibadan" },
			{ name: "Ogbomosho" },
			{ name: "Oyo" },
			{ name: "Iseyin" },
			{ name: "Saki" },
		],
		KD: [
			{ name: "Kaduna" },
			{ name: "Zaria" },
			{ name: "Kafanchan" },
			{ name: "Kagoro" },
		],
		AN: [
			{ name: "Awka" },
			{ name: "Onitsha" },
			{ name: "Nnewi" },
			{ name: "Ekwulobia" },
		],
		EN: [
			{ name: "Enugu" },
			{ name: "Nsukka" },
			{ name: "Agbani" },
			{ name: "Oji River" },
		],
		ED: [
			{ name: "Benin City" },
			{ name: "Auchi" },
			{ name: "Ekpoma" },
			{ name: "Uromi" },
		],
		DE: [
			{ name: "Asaba" },
			{ name: "Warri" },
			{ name: "Sapele" },
			{ name: "Ughelli" },
		],
		IM: [
			{ name: "Owerri" },
			{ name: "Orlu" },
			{ name: "Okigwe" },
		],
		AB: [
			{ name: "Umuahia" },
			{ name: "Aba" },
			{ name: "Arochukwu" },
		],
		AK: [
			{ name: "Uyo" },
			{ name: "Ikot Ekpene" },
			{ name: "Eket" },
		],
	},
	GH: {
		AA: [
			{ name: "Accra" },
			{ name: "Tema" },
			{ name: "Madina" },
			{ name: "Teshie" },
			{ name: "Nungua" },
			{ name: "Labadi" },
			{ name: "Osu" },
			{ name: "Dansoman" },
			{ name: "Kaneshie" },
			{ name: "Achimota" },
		],
		AH: [
			{ name: "Kumasi" },
			{ name: "Obuasi" },
			{ name: "Suame" },
			{ name: "Ejisu" },
			{ name: "Konongo" },
			{ name: "Mampong" },
		],
		CP: [
			{ name: "Cape Coast" },
			{ name: "Elmina" },
			{ name: "Winneba" },
			{ name: "Kasoa" },
		],
		WP: [
			{ name: "Sekondi-Takoradi" },
			{ name: "Tarkwa" },
			{ name: "Axim" },
		],
		EP: [
			{ name: "Koforidua" },
			{ name: "Akosombo" },
			{ name: "Mpraeso" },
		],
	},
	KE: {
		NBO: [
			{ name: "Nairobi" },
			{ name: "Westlands" },
			{ name: "Karen" },
			{ name: "Kilimani" },
			{ name: "Parklands" },
			{ name: "Lavington" },
			{ name: "Kileleshwa" },
			{ name: "Embakasi" },
			{ name: "Kasarani" },
			{ name: "Dagoretti" },
		],
		MBA: [
			{ name: "Mombasa" },
			{ name: "Nyali" },
			{ name: "Bamburi" },
			{ name: "Likoni" },
			{ name: "Changamwe" },
		],
		KSM: [
			{ name: "Kisumu" },
			{ name: "Ahero" },
			{ name: "Maseno" },
		],
		NKR: [
			{ name: "Nakuru" },
			{ name: "Naivasha" },
			{ name: "Gilgil" },
		],
		ELD: [
			{ name: "Eldoret" },
			{ name: "Turbo" },
			{ name: "Burnt Forest" },
		],
	},
	ZA: {
		GT: [
			{ name: "Johannesburg" },
			{ name: "Pretoria" },
			{ name: "Soweto" },
			{ name: "Sandton" },
			{ name: "Randburg" },
			{ name: "Roodepoort" },
			{ name: "Benoni" },
			{ name: "Boksburg" },
			{ name: "Germiston" },
			{ name: "Krugersdorp" },
		],
		WC: [
			{ name: "Cape Town" },
			{ name: "Stellenbosch" },
			{ name: "Paarl" },
			{ name: "Somerset West" },
			{ name: "Bellville" },
			{ name: "George" },
			{ name: "Mossel Bay" },
		],
		KZN: [
			{ name: "Durban" },
			{ name: "Pietermaritzburg" },
			{ name: "Richards Bay" },
			{ name: "Newcastle" },
		],
		EC: [
			{ name: "Port Elizabeth" },
			{ name: "East London" },
			{ name: "Mthatha" },
		],
	},
	GB: {
		ENG: [
			{ name: "London" },
			{ name: "Birmingham" },
			{ name: "Manchester" },
			{ name: "Liverpool" },
			{ name: "Leeds" },
			{ name: "Sheffield" },
			{ name: "Bristol" },
			{ name: "Newcastle" },
			{ name: "Nottingham" },
			{ name: "Leicester" },
		],
		SCT: [
			{ name: "Edinburgh" },
			{ name: "Glasgow" },
			{ name: "Aberdeen" },
			{ name: "Dundee" },
		],
		WLS: [
			{ name: "Cardiff" },
			{ name: "Swansea" },
			{ name: "Newport" },
		],
		NIR: [
			{ name: "Belfast" },
			{ name: "Derry" },
			{ name: "Lisburn" },
		],
	},
	CA: {
		ON: [
			{ name: "Toronto" },
			{ name: "Ottawa" },
			{ name: "Mississauga" },
			{ name: "Brampton" },
			{ name: "Hamilton" },
			{ name: "London" },
			{ name: "Markham" },
		],
		QC: [
			{ name: "Montreal" },
			{ name: "Quebec City" },
			{ name: "Laval" },
			{ name: "Gatineau" },
		],
		BC: [
			{ name: "Vancouver" },
			{ name: "Surrey" },
			{ name: "Burnaby" },
			{ name: "Richmond" },
			{ name: "Victoria" },
		],
		AB: [
			{ name: "Calgary" },
			{ name: "Edmonton" },
			{ name: "Red Deer" },
			{ name: "Lethbridge" },
		],
	},
	DZ: {
		AL: [
			{ name: "Algiers" },
			{ name: "Bab Ezzouar" },
			{ name: "Birkhadem" },
			{ name: "Draria" },
			{ name: "El Harrach" },
		],
		OR: [
			{ name: "Oran" },
			{ name: "Gdyel" },
			{ name: "Bethioua" },
			{ name: "Arzew" },
			{ name: "Mers El Kebir" },
		],
		CN: [
			{ name: "Constantine" },
			{ name: "Didouche Mourad" },
			{ name: "Hamma Bouziane" },
			{ name: "Ibn Ziad" },
		],
	},
	AO: {
		LU: [
			{ name: "Luanda" },
			{ name: "Viana" },
			{ name: "Belas" },
			{ name: "Cacuaco" },
			{ name: "Cazenga" },
		],
		HU: [
			{ name: "Huambo" },
			{ name: "Londuimbale" },
			{ name: "Caála" },
			{ name: "Chicala Choloanga" },
		],
		BG: [
			{ name: "Lobito" },
			{ name: "Benguela" },
			{ name: "Baía Farta" },
			{ name: "Catumbela" },
		],
	},
	BW: {
		GB: [
			{ name: "Gaborone" },
			{ name: "Lobatse" },
			{ name: "Molepolole" },
			{ name: "Ramotswa" },
		],
		FB: [
			{ name: "Francistown" },
			{ name: "Mmadinare" },
			{ name: "Moshupa" },
		],
	},
	CM: {
		LT: [
			{ name: "Douala" },
			{ name: "Loum" },
			{ name: "Edea" },
			{ name: "Manjo" },
		],
		SW: [
			{ name: "Buea" },
			{ name: "Limbe" },
			{ name: "Mamfe" },
			{ name: "Tiko" },
		],
		WE: [
			{ name: "Bamenda" },
			{ name: "Nkambe" },
			{ name: "Fundong" },
			{ name: "Wum" },
		],
		CE: [
			{ name: "Yaoundé" },
			{ name: "Mfoundi" },
			{ name: "Soa" },
			{ name: "Mfou" },
		],
	},
	AU: {
		NSW: [
			{ name: "Sydney" },
			{ name: "Newcastle" },
			{ name: "Central Coast" },
			{ name: "Wollongong" },
		],
		QLD: [
			{ name: "Brisbane" },
			{ name: "Gold Coast" },
			{ name: "Sunshine Coast" },
			{ name: "Townsville" },
		],
		VIC: [
			{ name: "Melbourne" },
			{ name: "Geelong" },
			{ name: "Ballarat" },
			{ name: "Bendigo" },
		],
		WA: [
			{ name: "Perth" },
			{ name: "Fremantle" },
			{ name: "Mandurah" },
			{ name: "Geraldton" },
		],
		SA: [
			{ name: "Adelaide" },
			{ name: "Mount Gambier" },
			{ name: "Murray Bridge" },
			{ name: "Port Augusta" },
		],
	},
	BR: {
		SP: [
			{ name: "São Paulo" },
			{ name: "Campinas" },
			{ name: "Santo André" },
			{ name: "Guarulhos" },
		],
		RJ: [
			{ name: "Rio de Janeiro" },
			{ name: "São Gonçalo" },
			{ name: "Duque de Caxias" },
			{ name: "Nova Iguaçu" },
		],
		MG: [
			{ name: "Belo Horizonte" },
			{ name: "Uberlândia" },
			{ name: "Contagem" },
			{ name: "Juiz de Fora" },
		],
		BA: [
			{ name: "Salvador" },
			{ name: "Feira de Santana" },
			{ name: "Vitória da Conquista" },
			{ name: "Camaçari" },
		],
	},
	FR: {
		IDF: [
			{ name: "Paris" },
			{ name: "Boulogne-Billancourt" },
			{ name: "Saint-Denis" },
			{ name: "Créteil" },
		],
		PAC: [
			{ name: "Marseille" },
			{ name: "Nice" },
			{ name: "Aix-en-Provence" },
			{ name: "Toulon" },
		],
		ARA: [
			{ name: "Lyon" },
			{ name: "Saint-Étienne" },
			{ name: "Grenoble" },
			{ name: "Annecy" },
		],
	},
	DE: {
		BY: [
			{ name: "Munich" },
			{ name: "Nuremberg" },
			{ name: "Augsburg" },
			{ name: "Regensburg" },
		],
		BE: [
			{ name: "Berlin" },
			{ name: "Mitte" },
			{ name: "Charlottenburg" },
			{ name: "Kreuzberg" },
		],
		HE: [
			{ name: "Frankfurt" },
			{ name: "Wiesbaden" },
			{ name: "Offenbach" },
			{ name: "Hanau" },
		],
	},
	IT: {
		LOM: [
			{ name: "Milan" },
			{ name: "Bergamo" },
			{ name: "Brescia" },
			{ name: "Como" },
		],
		LAZ: [
			{ name: "Rome" },
			{ name: "Latina" },
			{ name: "Frosinone" },
			{ name: "Viterbo" },
		],
		CAM: [
			{ name: "Naples" },
			{ name: "Salerno" },
			{ name: "Avellino" },
			{ name: "Benevento" },
		],
	},
	ES: {
		AND: [
			{ name: "Seville" },
			{ name: "Málaga" },
			{ name: "Granada" },
			{ name: "Córdoba" },
		],
		CAT: [
			{ name: "Barcelona" },
			{ name: "L'Hospitalet de Llobregat" },
			{ name: "Badalona" },
			{ name: "Terrassa" },
		],
		MAD: [
			{ name: "Madrid" },
			{ name: "Móstoles" },
			{ name: "Leganés" },
			{ name: "Fuenlabrada" },
		],
	},
	JP: {
		13: [
			{ name: "Tokyo" },
			{ name: "Yokohama" },
			{ name: "Suginami" },
			{ name: "Shibuya" },
			{ name: "Shinjuku" },
			{ name: "Meguro" },
			{ name: "Setagaya" },
		],
		27: [
			{ name: "Osaka" },
			{ name: "Sakai" },
			{ name: "Higashiosaka" },
			{ name: "Hirakata" },
			{ name: "Kadoma" },
			{ name: "Suita" },
		],
		14: [
			{ name: "Yokohama" },
			{ name: "Kawasaki" },
			{ name: "Sagamihara" },
			{ name: "Hiratsuka" },
			{ name: "Odawara" },
			{ name: "Fujisawa" },
		],
		23: [
			{ name: "Nagoya" },
			{ name: "Toyota" },
			{ name: "Okazaki" },
			{ name: "Ichinomiya" },
		],
		11: [
			{ name: "Saitama" },
			{ name: "Kawaguchi" },
			{ name: "Kawagoe" },
			{ name: "Tokorozawa" },
		],
		12: [
			{ name: "Chiba" },
			{ name: "Funabashi" },
			{ name: "Matsudo" },
			{ name: "Ichikawa" },
		],
		28: [
			{ name: "Kobe" },
			{ name: "Himeji" },
			{ name: "Amagasaki" },
			{ name: "Nishinomiya" },
		],
		40: [
			{ name: "Fukuoka" },
			{ name: "Kitakyushu" },
			{ name: "Kurume" },
			{ name: "Iizuka" },
		],
		22: [
			{ name: "Shizuoka" },
			{ name: "Hamamatsu" },
			{ name: "Numazu" },
			{ name: "Atami" },
		],
		1: [
			{ name: "Sapporo" },
			{ name: "Asahikawa" },
			{ name: "Hakodate" },
			{ name: "Kushiro" },
		],
	},
	IN: {
		MH: [
			{ name: "Mumbai" },
			{ name: "Pune" },
			{ name: "Nagpur" },
			{ name: "Thane" },
			{ name: "Nashik" },
			{ name: "Kalyan-Dombivali" },
		],
		UP: [
			{ name: "Lucknow" },
			{ name: "Kanpur" },
			{ name: "Ghaziabad" },
			{ name: "Agra" },
			{ name: "Varanasi" },
			{ name: "Meerut" },
		],
		TN: [
			{ name: "Chennai" },
			{ name: "Coimbatore" },
			{ name: "Madurai" },
			{ name: "Salem" },
			{ name: "Tiruchirappalli" },
			{ name: "Madurai" },
		],
		KA: [
			{ name: "Bangalore" },
			{ name: "Mysore" },
			{ name: "Mangalore" },
			{ name: "Hubli" },
		],
		GJ: [
			{ name: "Ahmedabad" },
			{ name: "Surat" },
			{ name: "Vadodara" },
			{ name: "Rajkot" },
		],
		RJ: [
			{ name: "Jaipur" },
			{ name: "Jodhpur" },
			{ name: "Kota" },
			{ name: "Bikaner" },
		],
		HR: [
			{ name: "Faridabad" },
			{ name: "Gurgaon" },
			{ name: "Hisar" },
			{ name: "Sonipat" },
		],
		KL: [
			{ name: "Thiruvananthapuram" },
			{ name: "Kochi" },
			{ name: "Kozhikode" },
			{ name: "Palakkad" },
		],
		PB: [
			{ name: "Ludhiana" },
			{ name: "Amritsar" },
			{ name: "Jalandhar" },
			{ name: "Patiala" },
		],
		WB: [
			{ name: "Kolkata" },
			{ name: "Siliguri" },
			{ name: "Asansol" },
			{ name: "Durgapur" },
		],
	},
	AR: {
		C: [
			{ name: "Buenos Aires" },
			{ name: "La Matanza" },
			{ name: "Lomas de Zamora" },
			{ name: "Mar del Plata" },
		],
		B: [
			{ name: "La Plata" },
			{ name: "Mar del Plata" },
			{ name: "Berazategui" },
			{ name: "Quilmes" },
		],
	},
	CL: {
		"13": [
			{ name: "Santiago" },
			{ name: "Puente Alto" },
			{ name: "Las Condes" },
			{ name: "La Florida" },
		],
		"08": [
			{ name: "Concepción" },
			{ name: "Talcahuano" },
			{ name: "Chiguayante" },
			{ name: "Los Ángeles" },
		],
	},
	CO: {
		DC: [
			{ name: "Bogotá" },
			{ name: "Soacha" },
			{ name: "Facatativá" },
			{ name: "Zipaquirá" },
		],
		ANT: [
			{ name: "Medellín" },
			{ name: "Itagüí" },
			{ name: "Envigado" },
			{ name: "Bello" },
		],
		VAC: [
			{ name: "Cali" },
			{ name: "Palmira" },
			{ name: "Buenaventura" },
			{ name: "Cartago" },
		],
		ATL: [
			{ name: "Barranquilla" },
			{ name: "Soledad" },
			{ name: "Malambo" },
			{ name: "Sabanalarga" },
		],
	},
	PE: {
		LIM: [
			{ name: "Lima" },
			{ name: "Callao" },
			{ name: "Miraflores" },
			{ name: "Surco" },
		],
		ARE: [
			{ name: "Arequipa" },
			{ name: "Mollendo" },
			{ name: "Cayma" },
			{ name: "Paucarpata" },
		],
		CUS: [
			{ name: "Cusco" },
			{ name: "Machu Picchu" },
			{ name: "Sicuani" },
			{ name: "Urubamba" },
		],
	},
	VE: {
		A: [
			{ name: "Caracas" },
			{ name: "Chacao" },
			{ name: "El Hatillo" },
			{ name: "Baruta" },
		],
		I: [
			{ name: "Maracaibo" },
			{ name: "Cabimas" },
			{ name: "Ciudad Ojeda" },
			{ name: "Altagracia de Orituco" },
		],
	},
	MX: {
		DIF: [
			{ name: "Mexico City" },
			{ name: "Ecatepec" },
			{ name: "Nezahualcóyotl" },
			{ name: "Guadalajara" },
		],
		GUA: [
			{ name: "Guadalajara" },
			{ name: "Zapopan" },
			{ name: "Tlaquepaque" },
			{ name: "Tonala" },
		],
		VER: [
			{ name: "Veracruz" },
			{ name: "Boca del Río" },
			{ name: "Coatzacoalcos" },
			{ name: "Córdoba" },
		],
		MEX: [
			{ name: "Toluca" },
			{ name: "Ecatepec" },
			{ name: "Naucalpan" },
			{ name: "Chimalhuacán" },
		],
	}
};

/**
 * Get states for a country
 */
export function getStatesForCountry(countryCode: string): State[] {
	return STATES_BY_COUNTRY[countryCode] || [];
}

/**
 * Get cities for a state in a country
 */
export function getCitiesForState(
	countryCode: string,
	stateCode: string,
): City[] {
	return CITIES_BY_STATE[countryCode]?.[stateCode] || [];
}

/**
 * Get country by code
 */
export function getCountryByCode(code: string): Country | undefined {
	return COUNTRIES.find((c) => c.code === code);
}

/**
 * Get country by name
 */
export function getCountryByName(name: string): Country | undefined {
	return COUNTRIES.find((c) => c.name === name);
}
